name: Cypress Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      spec:
        description: 'Arquivo de teste específico para executar'
        required: false
        default: 'cypress/e2e/**/*.cy.js'
      browser:
        description: 'Navegador para executar os testes'
        required: false
        default: 'chrome'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Configurar Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Verificar versão do Node e NPM
      run: |
        node --version
        npm --version

    - name: Instalar dependências
      run: |
        npm ci
      
    - name: Verificar instalação do Cypress
      run: |
        npx cypress verify

    - name: Executar testes Cypress
      run: |
        npx cypress run --browser ${{ github.event.inputs.browser || 'chrome' }} --spec "${{ github.event.inputs.spec || 'cypress/e2e/**/*.cy.js' }}"
      continue-on-error: true
      id: cypress-run

    - name: Upload de screenshots em caso de falha
      uses: actions/upload-artifact@v4
      if: failure() || success()
      with:
        name: cypress-screenshots
        path: cypress/screenshots
        retention-days: 30
        if-no-files-found: ignore

    - name: Upload de vídeos
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cypress-videos
        path: cypress/videos
        retention-days: 30
        if-no-files-found: ignore

    - name: Upload de relatórios
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cypress-reports
        path: cypress/reports
        retention-days: 30
        if-no-files-found: ignore

    - name: Verificar resultado dos testes
      if: steps.cypress-run.outcome != 'success'
      run: exit 1